name: app_ui
description: Application UI components holder.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  lucide_icons_flutter: ^1.1.2
  shadcn_ui: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
